/** Định nghĩa các trò trong Trung tâm giải trí (route + nhãn + ảnh nút). Ảnh có thể thay trong `public/images/entertainment/`. */
export const ENTERTAINMENT_GAMES = [
  {
    id: 'lucky-wheel',
    path: 'lucky-wheel',
    title: 'Vòng quay may mắn',
    description: 'Ô Peta, Peta Gold cố định + vật phẩm admin; lịch sử & lượt/ngày.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '',
  },
  {
    id: 'scratch-lottery',
    path: 'scratch-lottery',
    title: 'Vé số cào',
    description: 'Vé 3 ô và vé 5 ô — cào trùng hình nhận thưởng.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '',
  },
  {
    id: 'mystery-box',
    path: 'mystery-box',
    title: 'Hộp bí ẩn',
    description: 'Cho vào một vật phẩm, nhận ngẫu nhiên theo độ hiếm.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '',
  },
  {
    id: 'beggar-king',
    path: 'beggar-king',
    title: 'Vua ăn mày',
    description: 'Ghé Làng Phú Gia xin lì xì từ trưởng làng Richies — mỗi 12 giờ một lần.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '/images/background/langphugia.png',
  },
  {
    id: 'daily-free',
    path: 'daily-free',
    title: 'Vật phẩm miễn phí',
    description: 'Ghé Làng Nhân Ái nhận vật phẩm tặng — mỗi ngày một lần.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '',
  },
  {
    id: 'lucky-booth',
    path: 'lucky-booth',
    title: 'Xổ số (Lucky booth)',
    description: 'Chọn dãy 4 chữ số, trúng nhận Peta cao.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '',
  },
  {
    id: 'slot-machine',
    path: 'slot-machine',
    title: 'Máy đánh bạc',
    description: 'Làng Đỏ Đen — Máy đánh bạc trên Hỏa Diệm Sơn.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '/images/background/langdoden.png',
  },
  {
    id: 'guess-number',
    path: 'guess-number',
    title: 'Đoán số',
    description: 'Làng Trẻ Con — đoán cao hơn / thấp hơn mốc, nhận Peta.',
    imgSrc: '/images/entertainment/game-tile-placeholder.svg',
    pageBackgroundSrc: '/images/background/ice.png',
  },
];
